"""change DB structure so that an index can be built out of coin entries

Revision ID: d3386282a987
Revises: ffd2abf69221
Create Date: 2022-06-30 13:38:25.065413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3386282a987'
down_revision = 'ffd2abf69221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consists_of')
    op.add_column('coins', sa.Column('index_id', sa.Integer(), nullable=True))
    op.add_column('coins', sa.Column('id', sa.String(length=256), nullable=False))
    op.add_column('coins', sa.Column('proportion_invested', sa.Numeric(), nullable=False))
    op.add_column('coins', sa.Column('personal_index_market_share', sa.Numeric(), nullable=False))
    op.create_foreign_key(None, 'coins', 'indices', ['index_id'], ['index_id'], ondelete='CASCADE')
    op.drop_column('coins', 'circulating_supply')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('circulating_supply', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coins', type_='foreignkey')
    op.drop_column('coins', 'personal_index_market_share')
    op.drop_column('coins', 'proportion_invested')
    op.drop_column('coins', 'id')
    op.drop_column('coins', 'index_id')
    op.create_table('consists_of',
    sa.Column('coin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_of_coin', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.coin_id'], name='consists_of_coin_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_id'], ['indices.index_id'], name='consists_of_index_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
