"""add column total_investment to Index

Revision ID: dbfdba298da2
Revises: d3386282a987
Create Date: 2022-06-30 15:39:23.175269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfdba298da2'
down_revision = 'd3386282a987'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('total_investment', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indices', 'total_investment')
    # ### end Alembic commands ###
