"""inital version with seperated tables for coins, index and consists_of

Revision ID: ffd2abf69221
Revises: 
Create Date: 2022-06-30 13:35:23.630425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd2abf69221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consists_of', sa.Column('coin_id', sa.Integer(), nullable=False))
    op.add_column('consists_of', sa.Column('index_id', sa.Integer(), nullable=False))
    op.add_column('consists_of', sa.Column('amount_of_coin', sa.Numeric(), nullable=False))
    op.create_foreign_key(None, 'consists_of', 'indices', ['index_id'], ['index_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'consists_of', 'coins', ['coin_id'], ['coin_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consists_of', type_='foreignkey')
    op.drop_constraint(None, 'consists_of', type_='foreignkey')
    op.drop_column('consists_of', 'amount_of_coin')
    op.drop_column('consists_of', 'index_id')
    op.drop_column('consists_of', 'coin_id')
    # ### end Alembic commands ###
