name: Build and Deploy Code

on:
  push:

 env:
  DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
  DATABASE_PORT: ${{secrets.DATABASE_PORT}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  DATABASE_NAME: ${{secrets.DATABASE_NAME}}
  DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  ALGORITHM: ${{secrets.ALGORITHM}}
  ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

jobs:
  test:
   
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  deploy-backend:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: deploying backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_BACKEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # procfile: "web: uvicorn app.main:app --host=0.0.0.0 --port=${PORT:-8000}"
          appdir: "backend"
  deploy-frontend:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: deploying frontend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_FRONTEND}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "frontend"

  #     # - name: deploy to ubuntu server
  #     #   uses: appleboy/ssh-action@master
  #     #   with:
  #     #     host: ${{secrets.PROD_HOST}}
  #     #     username: ${{secrets.PROD_USERNAME}}
  #     #     password: ${{secrets.PROD_PASSWORD}}
  #     #     script: |
  #     #       cd app/src
  #     #       git pull
  #     #       echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart api
